//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HUC.Web.Models.SinglePoint
{
    using System;
    using System.Collections.Generic;
    
    public partial class Applications
    {
        public Applications()
        {
            this.UsersApplications = new HashSet<UsersApplications>();
        }
    
        public int ID { get; set; }
        public string Application_Name { get; set; }
        public string Application_Description { get; set; }
        public string Icon { get; set; }
        public string Modal_Name { get; set; }
        public string App_Url { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual ICollection<UsersApplications> UsersApplications { get; set; }
    }
}
