//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HUC.Web.Models.SinglePoint
{
    using System;
    using System.Collections.Generic;
    
    public partial class DentonsEmployeesSettings
    {
        public string MailServer { get; set; }
        public int SMTPPort { get; set; }
        public bool EnableSSL { get; set; }
        public string MailUsername { get; set; }
        public string MailPassword { get; set; }
        public string DentonsEmployeesURL { get; set; }
        public bool TwoFAEnable { get; set; }
        public int ID { get; set; }
        public string License { get; set; }
        public string HashCode { get; set; }
        public string CompanyName { get; set; }
        public string CompanyLogo { get; set; }
        public string CompanyAddress { get; set; }
    }
}
